// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcG7Rc7EjZaymA73Uotm3zgKXXbJ8IY4Y',
    appId: '1:390282525436:web:2c564a25e9db3cef437579',
    messagingSenderId: '390282525436',
    projectId: 'pract9-9c1b4',
    authDomain: 'pract9-9c1b4.firebaseapp.com',
    storageBucket: 'pract9-9c1b4.firebasestorage.app',
    measurementId: 'G-EBFRNCW25N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8UHn3s3eIUJ65uBKKjeKPSDPvyCt8hnY',
    appId: '1:390282525436:android:e01cfacc8a8da044437579',
    messagingSenderId: '390282525436',
    projectId: 'pract9-9c1b4',
    storageBucket: 'pract9-9c1b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByNwSOnPy1vV0zupXfpVKEWkC_Sc39s9w',
    appId: '1:390282525436:ios:12ff0debb33c6f0d437579',
    messagingSenderId: '390282525436',
    projectId: 'pract9-9c1b4',
    storageBucket: 'pract9-9c1b4.firebasestorage.app',
    iosBundleId: 'com.example.prakt9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByNwSOnPy1vV0zupXfpVKEWkC_Sc39s9w',
    appId: '1:390282525436:ios:12ff0debb33c6f0d437579',
    messagingSenderId: '390282525436',
    projectId: 'pract9-9c1b4',
    storageBucket: 'pract9-9c1b4.firebasestorage.app',
    iosBundleId: 'com.example.prakt9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcG7Rc7EjZaymA73Uotm3zgKXXbJ8IY4Y',
    appId: '1:390282525436:web:a5cab52714721957437579',
    messagingSenderId: '390282525436',
    projectId: 'pract9-9c1b4',
    authDomain: 'pract9-9c1b4.firebaseapp.com',
    storageBucket: 'pract9-9c1b4.firebasestorage.app',
    measurementId: 'G-PS7C99WDPN',
  );

}