// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGm44-ndtJKP_NFSUbGctHAOtDhvX5quk',
    appId: '1:416539327201:web:b52e8c276e16e3903ad5a0',
    messagingSenderId: '416539327201',
    projectId: 'lalanguage-11488',
    authDomain: 'lalanguage-11488.firebaseapp.com',
    storageBucket: 'lalanguage-11488.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9kW9m99i69l8pm-l8qz0qRf12M9PtXWc',
    appId: '1:416539327201:android:00f35e9dd75c10ad3ad5a0',
    messagingSenderId: '416539327201',
    projectId: 'lalanguage-11488',
    storageBucket: 'lalanguage-11488.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCca0xcS1WYYznQJ-0oPNeRdx_ejRXe_jM',
    appId: '1:416539327201:ios:8d9170a3e7af49333ad5a0',
    messagingSenderId: '416539327201',
    projectId: 'lalanguage-11488',
    storageBucket: 'lalanguage-11488.firebasestorage.app',
    iosBundleId: 'com.example.lalalanguage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCca0xcS1WYYznQJ-0oPNeRdx_ejRXe_jM',
    appId: '1:416539327201:ios:8d9170a3e7af49333ad5a0',
    messagingSenderId: '416539327201',
    projectId: 'lalanguage-11488',
    storageBucket: 'lalanguage-11488.firebasestorage.app',
    iosBundleId: 'com.example.lalalanguage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGm44-ndtJKP_NFSUbGctHAOtDhvX5quk',
    appId: '1:416539327201:web:29e78424d40e54d03ad5a0',
    messagingSenderId: '416539327201',
    projectId: 'lalanguage-11488',
    authDomain: 'lalanguage-11488.firebaseapp.com',
    storageBucket: 'lalanguage-11488.firebasestorage.app',
  );
}
